# 학습이 잘 되는 모델


*   사용할 레이어
  - tf.keras.layers.BatchNomalization()
  - tf.keras.layers.Activation('swish')
*   데이터
  - 보스턴 집값 예측 : (링크 생략)
  - 아이리스 품종 분류 : (링크 생략)



보스턴 집값 예측

In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
# 1. 과거의 데이터 준비
file_url = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
boston = pd.read_csv(file_url)
print(boston.columns)
boston.head()

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')


crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
# 독립변수, 종속변수 분리
id_var = boston[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
d_var = boston[['medv']]
print(id_var.shape, d_var.shape)

(506, 13) (506, 1)


In [ ]:
# 2. 모델의 구조 만들기
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
# Activation을 분리해서 적어준다.(위의 모델과 동일)
# Batchn normalization을 Dense layer와 Activation layer 사이에 적어주는 것이 좋다.

X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [ ]:
# 4. 데이터로 모델 학습(FIT)
model.fit(id_var, d_var, epochs=1000)

Epoch 1/1000
16/16 [==============================] - 0s 3ms/step - loss: 616.3967
Epoch 2/1000
16/16 [==============================] - 0s 3ms/step - loss: 610.4193
Epoch 3/1000
16/16 [==============================] - 0s 3ms/step - loss: 605.1581
Epoch 4/1000
16/16 [==============================] - 0s 3ms/step - loss: 600.3618
Epoch 5/1000
16/16 [==============================] - 0s 3ms/step - loss: 595.8484
Epoch 6/1000
16/16 [==============================] - 0s 4ms/step - loss: 591.0505
Epoch 7/1000
16/16 [==============================] - 0s 3ms/step - loss: 586.9481
Epoch 8/1000
16/16 [==============================] - 0s 3ms/step - loss: 582.8610
Epoch 9/1000
16/16 [==============================] - 0s 3ms/step - loss: 578.8375
Epoch 10/1000
16/16 [==============================] - 0s 3ms/step - loss: 575.5132
Epoch 11/1000
16/16 [==============================] - 0s 4ms/step - loss: 571.5992
Epoch 12/1000
16/16 [==============================] - 0s 3ms/step - loss: 567.7758
E

In [ ]:
model.summary()

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 5. 모델 이용하기
print(model.predict(id_var[:5]))
print(d_var[:5])

[[28.655827]
 [24.06188 ]
 [30.360355]
 [31.126366]
 [30.295172]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [ ]:
d_var[0:5]

medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2

In [ ]:
# 모델의 수식 확인
model.get_weights()

[array([[-1.48636207e-01,  2.66249590e-02, -9.35235918e-02,
         -4.23787743e-01, -3.08118671e-01, -1.92385480e-01,
          3.95542741e-01,  1.08864002e-01,  1.17702377e+00,
         -2.06552833e-01],
        [ 3.37465219e-02,  1.48196205e-01,  6.96649356e-03,
         -3.52301985e-01, -2.22565219e-01,  4.95381266e-01,
         -7.64640749e-01, -3.16514701e-01, -3.36789757e-01,
         -4.12891358e-01],
        [-8.87916423e-03,  1.89596385e-01,  2.59075612e-02,
         -2.73342580e-01, -6.13420367e-01, -2.85586625e-01,
         -4.53251839e-01, -1.37157336e-01, -1.36806071e+00,
         -3.88952196e-02],
        [ 1.16813965e-01,  1.10416877e+00, -1.67767918e+00,
          1.84508121e+00,  1.28534257e+00, -1.31341413e-01,
         -2.27493674e-01, -1.62176478e+00, -1.40910375e+00,
         -1.05649471e-01],
        [-3.06732506e-01,  2.10107164e-03, -7.42075443e-01,
          5.54817617e-01,  4.00202662e-01,  3.18839937e-01,
         -3.17573696e-01, -3.28461796e-01,  1.459342

아이리스 품종 분류

In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
# 1. 과거의 데이터 준비
file_url = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file_url)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
# 원핫인코딩
encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
print(encoding.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
# 독립변수, 종속변수 분리
id_var = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
d_var = encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(id_var.shape, d_var.shape)

(150, 4) (150, 3)


In [ ]:
# 2. 모델 구조 만들기
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(X)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy', metrics = 'accuracy')

In [ ]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy', metrics = 'accuracy')

In [ ]:
# 3. 모델 학습(FIT)
model.fit(id_var, d_var, epochs=1000)

Epoch 1/1000
5/5 [==============================] - 0s 4ms/step - loss: 1.9320 - accuracy: 0.0200
Epoch 2/1000
5/5 [==============================] - 0s 5ms/step - loss: 1.8556 - accuracy: 0.0400
Epoch 3/1000
5/5 [==============================] - 0s 4ms/step - loss: 1.7785 - accuracy: 0.0600
Epoch 4/1000
5/5 [==============================] - 0s 4ms/step - loss: 1.7350 - accuracy: 0.0333
Epoch 5/1000
5/5 [==============================] - 0s 4ms/step - loss: 1.6762 - accuracy: 0.0600
Epoch 6/1000
5/5 [==============================] - 0s 4ms/step - loss: 1.6509 - accuracy: 0.0400
Epoch 7/1000
5/5 [==============================] - 0s 4ms/step - loss: 1.5875 - accuracy: 0.1000
Epoch 8/1000
5/5 [==============================] - 0s 3ms/step - loss: 1.5568 - accuracy: 0.0867
Epoch 9/1000
5/5 [==============================] - 0s 3ms/step - loss: 1.5168 - accuracy: 0.0733
Epoch 10/1000
5/5 [==============================] - 0s 4ms/step - loss: 1.4742 - accuracy: 0.1200
Epoch 11/1000
5/5 [

In [ ]:
# 4. 모델 이용 
print(model.predict(id_var[0:5]))
print(d_var[0:5])

[[9.8369133e-01 1.5743677e-02 5.6501757e-04]
 [9.7357255e-01 2.5299929e-02 1.1275671e-03]
 [9.7661102e-01 2.2343397e-02 1.0455390e-03]
 [9.6625531e-01 3.1977862e-02 1.7668112e-03]
 [9.8376924e-01 1.5643466e-02 5.8736844e-04]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
print(d_var[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [ ]:
# 가중치 출력
model.get_weights()

[array([[ 0.35851312, -0.20787519,  0.406441  ,  0.42702794, -0.34034085,
         -0.04874651, -0.35849848,  0.46872535],
        [ 0.78493214,  0.10361113, -0.45050746,  0.70249647, -0.8896472 ,
         -0.05737855,  0.15417929, -0.22564796],
        [ 0.11020337,  0.7603216 ,  0.5820131 , -0.23783864, -0.06839648,
          0.22370131,  0.60517454,  0.01541524],
        [-0.4011593 ,  0.6135682 ,  0.5883406 , -0.12540627, -0.37688014,
          0.9055181 ,  0.9537571 , -0.6402421 ]], dtype=float32),
 array([ 0.01681831,  0.02063465, -0.3536868 ,  0.16925733, -0.29726306,
        -0.09559915,  0.05579796,  0.25063255], dtype=float32),
 array([[ 0.63780504, -0.19455373,  0.03330301],
        [-0.85469794,  0.15019533,  0.17090937],
        [-0.8412596 , -0.44189993, -0.4120319 ],
        [ 0.20064192,  0.1551674 , -0.5495472 ],
        [ 0.22383226,  0.36009586,  0.22520006],
        [-0.93261683,  0.30177683,  1.0180303 ],
        [-1.0067475 ,  0.10335445,  0.5432461 ],
        [ 0