## 아이리스 품종 분류



In [ ]:
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
# 1. 과거의 데이터 준비
file_url = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
iris = pd.read_csv(file_url)
iris.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [ ]:
# 원핫인코딩
encoding = pd.get_dummies(iris)
encoding.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
print(encoding.columns)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


In [ ]:
# 독립변수, 종속변수 분리
id_var = encoding[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
d_var = encoding[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(id_var.shape, d_var.shape)

(150, 4) (150, 3)


In [ ]:
# 2. 모델 구조 만들기
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(X)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss = 'categorical_crossentropy', metrics = 'accuracy')

In [ ]:
# 3. 모델 학습(FIT)
model.fit(id_var, d_var, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 4ms/step - loss: 1.6808 - accuracy: 0.1133
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 1.6185 - accuracy: 0.0800
Epoch 3/100
5/5 [==============================] - 0s 3ms/step - loss: 1.5748 - accuracy: 0.0400
Epoch 4/100
5/5 [==============================] - 0s 3ms/step - loss: 1.5390 - accuracy: 0.0267
Epoch 5/100
5/5 [==============================] - 0s 3ms/step - loss: 1.5061 - accuracy: 0.0200
Epoch 6/100
5/5 [==============================] - 0s 3ms/step - loss: 1.4767 - accuracy: 0.0400
Epoch 7/100
5/5 [==============================] - 0s 3ms/step - loss: 1.4500 - accuracy: 0.0667
Epoch 8/100
5/5 [==============================] - 0s 3ms/step - loss: 1.4240 - accuracy: 0.0867
Epoch 9/100
5/5 [==============================] - 0s 3ms/step - loss: 1.3993 - accuracy: 0.1200
Epoch 10/100
5/5 [==============================] - 0s 3ms/step - loss: 1.3765 - accuracy: 0.1867
Epoch 11/100
5/5 [===========

In [ ]:
# 4. 모델 이용 
print(model.predict(id_var[0:5]))
print(d_var[0:5])

[[0.48775038 0.23096666 0.28128296]
 [0.47380802 0.23573993 0.2904521 ]
 [0.48622194 0.22871508 0.285063  ]
 [0.47598964 0.23290552 0.29110482]
 [0.49051425 0.22969069 0.2797951 ]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [ ]:
print(d_var[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [ ]:
# 가중치 출력
model.get_weights()

[array([[ 0.6240761 , -0.14775524, -0.35049018],
        [ 0.7878629 ,  0.14377181, -0.76220644],
        [-1.9494735 , -0.03141428,  0.78815985],
        [-0.91945356,  0.4558047 ,  0.9963187 ]], dtype=float32),
 array([ 0.70686567,  0.34988424, -0.6007738 ], dtype=float32)]